### PR TITLE
Push image to GitHub Container Registry

### PR DESCRIPTION
**Pull request by Zertz**
Tested on my account: https://github.com/Zertz/regview/pkgs/container/regview

### CODE REVIEW

**Comment by ricardobranco777** [comment]
Thanks a lot!  I really appreciate it.

**Comment by Zertz** [comment]
@ricardobranco777 I'm not sure if that was intentional but you closed the PR without merging.

**Comment by ricardobranco777** [comment]
> @ricardobranco777 I'm not sure if that was intentional but you closed the PR without merging.

@Zertz I squashed the commits.  The status is Merged.  Now I can pull the image :)

But I get these error messages:
https://github.com/ricardobranco777/regview/actions/runs/5068957620

> denied: permission_denied: write_package
> Error: Process completed with exit code 1.

and 4 warnings:

> dockerloginbuildpush
> The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I can look into it later but if you already know the fix I would be grateful.

**Comment by Zertz** [comment]
Oh, yes, my bad I forgot to mention you need to turn on read/write permissions in _Settings_ -> _Actions_ -> _General_ -> _Workflow permissions_:

image

**Comment by Zertz** [comment]
I hadn't noticed the warnings but now that you mention it, I'm pretty sure updating to `actions/checkout@v3` should fix them.

**Comment by ricardobranco777** [comment]
> I hadn't noticed the warnings but now that you mention it, I'm pretty sure updating to `actions/checkout@v3` should fix them.

Tested it in another branch and it works. Thanks!

**Comment by ricardobranco777** [comment]
> I hadn't noticed the warnings but now that you mention it, I'm pretty sure updating to `actions/checkout@v3` should fix them.

The issue is with docker/login-action@v1.  Will update it to v2.  Wrt the settings above, I have the same and it's still failing.

**Comment by Zertz** [comment]
That's odd, I'm not sure what else could trigger that error 🤔

**Comment by ricardobranco777** [comment]
I finally had time to fix it.

**Pull request merged**
